- name: Install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: start and enable mysql server
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: install python mysql dependencies
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip3.9

# check password already setup or not
- name: check DB connection
  community.mysql.mysql_info:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    filter: version
  ignore_errors: yes
  register: mysql_connect_check

- name: print output
  ansible.builtin.debug:
    msg: "output>>>>>> {{ mysql_connect_check }}"

- name: setup root user and password
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
  when: mysql_connect_check.failed is true
